### ISSUE TITLE
AnsibleUndefinedVariable: 'WDA_BUNDLEID' is undefined"after run ansible script

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#159] opened 2022-12-22 11:31 UTC
Steps:

1.Run Ansible script

Actual result:  "msg": "AnsibleUndefinedVariable: 'WDA_BUNDLEID' is undefined" error

**Comment by vdelendik** [comment] 2022-12-22 12:00
closing as not a bug. you reused your own copy of main.yml. But in main.yml.original I introduced new variable with comment:
```
# Override to use custom WDA bundle id: https://github.com/zebrunner/mcloud-agent#prepare-webdriveragentipa-file
WDA_BUNDLEID: com.facebook.WebDriverAgentRunner.xctrunner
```

I recommend to do regular `./zebruner.sh setup` which copy from original to yml and step by step move all settings from backup to new file

**Closed by vdelendik** 2022-12-22 12:00 UTC
Labels: bug, invalid

**Comment by dhreben** [comment] 2022-12-22 12:35
closed
