### ISSUE TITLE
Error: Unhandled rejection Error: spawn adb ENOENT

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#88] opened 2022-01-24 09:53 UTC
**Steps:**

1..zebrunner-farm restart udid

**Actual result:**  Device containers  restarts every 30 sec .Error: Unhandled rejection Error: spawn adb ENOENT

**NOTE:** **Repro only APPIUM_VERSION: 1.0-beta3**

```
2022-01-24T09:42:52.047Z INF/provider 8 [*] Subscribing to permanent channel "6s3J.......Cg=="
2022-01-24T09:42:52.052Z INF/db 8 [*] Connecting to rethinkdb:28015
2022-01-24T09:42:52.054Z INF/provider 8 [*] Sending output to "tcp://stf-triproxy-dev:7270"
2022-01-24T09:42:52.054Z INF/provider 8 [*] Receiving input from "tcp://stf-triproxy-dev:7250"
Unhandled rejection Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2022-01-24T09:43:21.689Z INF/util:lifecycle 8 [*] Winding down for graceful exit, with optional error :  SIGTERM
2022-01-24T09:43:21.692Z WRN/db 8 [*] Connection closed
Exit status: 0

```

**Comment by vdelendik** [comment] 2022-01-24 23:33
@dhreben, closing as can't reproduce. it seems like ansible wasn't executed with download after shutdown and pulling latest changes. As I see sometimes pulling public ECR images still require do be authenticated in docker. if you execute ansible with redownload you would see it. please, retest removing preliminary appium:1.0-beta3 image

**Closed by vdelendik** 2022-01-24 23:33 UTC
Labels: invalid

**Comment by dhreben** [comment] 2022-01-25 13:41
closing as can't reproduce
