### ISSUE TITLE
 iOS device is not available on STF after disconnect and connect to mac

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#263] opened 2023-11-02 09:09 UTC
**Steps:** 

1. Disconnect iPhone_11
2. Connect iPhone_11

**Actual result:**  iOS device is not available on STF after disconnect and connect to mac

**WorkAround:**
./zebrunner.sh start Udid on mcloud-agent

**logs:** 

```
solvd@idmcloud mcloud-agent % docker logs -f device-iPhone_11-00030448112B402E       
device info:  {"ActivationState":"Activated","BasebandActivationTicketVersion":"V2","BasebandCertId":524245983,"BasebandChipID":104,"BasebandKeyHashInformation":{"AKeyStatus":64,"SKeyStatus":2},"BasebandMasterKeyHash":"1B41607650EBF11C6B39F41CB267DC64C121A9BCF44DBA5D28F55ACC86361BBA366554CD57B4C466055803E1EF81C870","BasebandRegionSKU":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","BasebandSerialNumber":"nByLdQXCe3oAAAAA","BasebandStatus":"BBInfoAvailable","BasebandVersion":"5.00.00","BluetoothAddress":"f4:d4:88:57:70:66","BoardId":4,"BootSessionID":"AFD7DA59-F44B-4FBB-B610-B3A5454FED19","BrickState":false,"BuildVersion":"21A351","CPUArchitecture":"arm64e","CarrierBundleInfoArray":[],"CertID":524245983,"ChipID":32816,"ChipSerialNo":"nByLdQXCe3oAAAAA","DeviceClass":"iPhone","DeviceColor":"1","DeviceName":"iPhone_11","DieID":3470368222953518,"EthernetAddress":"f4:d4:88:4c:7e:7f","FirmwareVersion":"iBoot-10151.2.12","FusingStatus":3,"HardwareModel":"N104AP","HardwarePlatform":"t8030","HasSiDP":true,"HostAttached":true,"HumanReadableProductVersionString":"17.0.2","InternationalMobileEquipmentIdentity":"353061285550849","InternationalMobileEquipmentIdentity2":"353061285612839","MLBSerialNumber":"C7H14920XGNL73XAG","MobileEquipmentIdentifier":"35306128555084","MobileSubscriberCountryCode":"","MobileSubscriberNetworkCode":"","ModelNumber":"MHDG3","NonVolatileRAM":{"StartupMute":"MQ==","SystemAudioVolumeSaved":"MQ==","auto-boot":"dHJ1ZQ==","backlight-level":"MTQzMg==","backlight-nits":"MHgwMDllZmNkYw==","boot-args":"","bootdelay":"MA==","fm-activation-locked":"Tk8=","fm-spstatus":"WUVT","oblit-begins":"T2JsaXRUeXBlOiBPYmxpdGVyYXRlRGF0YVBhcnRpdGlvbi4gUmVhc29uOiBEaXNlbWJhcms=","obliteration":"aGFuZGxlX21lc3NhZ2U6IE9ibGl0ZXJhdGlvbiBDb21wbGV0ZQo=","ota-controllerVersion":"U1VTLTIuMA==","ota-original-base-os-version":"MjFBMzI5","usbcfwflasherResult":"Tm8gZXJyb3Jz"},"PairRecordProtectionClass":4,"PartitionType":"GUID_partition_scheme","PasswordProtected":false,"PkHash":"Hz9b38WSRX/cE6qam0xEfaM6v7nHw0ZdWjTPu2WOXVU=","ProductName":"iPhone OS","ProductType":"iPhone12,1","ProductVersion":"17.0.2","ProductionSOC":true,"ProtocolVersion":"2","ProximitySensorCalibration":"f3oABTIAHgAXV3tBzC1QQgAAyEIaJiBBesdZQgAAFkMaJiBBesdZQgAAFkNN4IlC8UFAwdhtyUTtZ8hERo3HRPq5x0S/5bJB0gOxQRsuokGgJapBAAAgQo8QMENR2AVCAABIQkfEJ0SVVidE4xkaRh1t0EPVHathASAIEvW4sUUEmQREqctfRQIAAAAAAACG","RegionInfo":"RU/A","SIMStatus":"kCTSIMSupportSIMStatusNotInserted","SIMTrayStatus":"kCTSIMSupportSIMTrayInsertedNoSIM","SerialNumber":"FFWGTDR8N73C","SoftwareBehavior":"AQAAAAAAAAAAAAAAAAAAAA==","SoftwareBundleVersion":"","SupportedDeviceFamilies":[1],"TelephonyCapability":true,"TimeIntervalSince1970":1698915735.900138,"TimeZone":"Europe/Minsk","TimeZoneOffsetFromUTC":10800,"TrustedHostAttached":true,"UniqueChipID":3470368222953518,"UniqueDeviceID":"00030-000C5448112B402E","UseRaptorCerts":true,"Uses24HourClock":false,"WiFiAddress":"f4:d4:88:57:98:8a","WirelessBoardSerialNumber":"F00022788B7E","kCTPostponementStatus":"kCTPostponementStatusActivated"}
Linked appium container is up and running.
2023-11-02T09:02:16.136Z INF/db 34 [0000-000C5448112B402E] Connecting to demo.zebrunner.farm:28015
2023-11-02T09:02:16.149Z INF/device:support:push 34 [00030-000C5448112B402E] Ios device sending output to "tcp://demo.zebrunner.farm:7270"
2023-11-02T09:02:16.155Z INF/ios-device 34 [00030-000C5448112B402E] Preparing device options:  {
  serial: '00030-000C5448112B402E',
  provider: 'mcloud-ios3',
  publicIp: 'demo.zebrunner.farm',
  endpoints: {
    sub: [ 'tcp://demo.zebrunner.farm:7250' ],
    push: [ 'tcp://demo.zebrunner.farm:7270' ],
    appDealer: [ 'tcp://demo.zebrunner.farm:7160' ],
    devDealer: [ 'tcp://demo.zebrunner.farm:7260' ]
  },
  groupTimeout: 3600000,
  storageUrl: 'https://demo.zebrunner.farm:443/',
  adbHost: '127.0.0.1',
  adbPort: 5037,
  screenJpegQuality: 30,
  screenPingInterval: 30000,
  screenPort: 7464,
  screenWsUrlPattern: 'wss://demo.zebrunner.farm:443/d/192.168.88.156/000-00048112B402E/7464/',
  connectUrlPattern: '192.168.88.156:<%= publicPort %>',
  connectPort: 8101,
  wdaHost: 'appium',
  wdaPort: 8100,
  vncInitialSize: [ 600, 800 ],
  heartbeatInterval: 10000,
  bootCompleteTimeout: 60000,
  muteMaster: 'never',
  lockRotation: false,
  cleanup: true,
  screenReset: true,
  udidStorage: false,
  iproxy: false,
  deviceName: 'iPhone_11',
  deviceType: 'Phone',
  host: '192.168.88.156'
}
2023-11-02T09:02:16.448Z INF/device:support:sub 34 [0000..........8112B402E] Receiving input from "tcp://demo.zebrunner.farm:7250"
2023-11-02T09:02:16.450Z INF/device:support:sub 34 [000...........8112B402E] Subscribing to permanent channel "*ALL"
2023-11-02T09:02:16.453Z INF/device:plugins:solo 34 [0000...........48112B402E] Subscribing to permanent channel "4M675745vd2QHgHQ6pDTjd9ipj8="
2023-11-02T09:02:16.455Z INF/wdaClient 34 [0000............2B402E] WdaClient.js initializing...
connecting to WdaMjpeg
2023-11-02T09:02:16.461Z INF/device:info 34 ..........[12......................B402E] device.name: iPhone_11
Connected to WdaMjpeg appium:8101
2023-11-02T09:02:34.682Z IMP/device:plugins:group 34 [000..............8112B402E] Now owned by "admin@fakedomain.com"
2023-11-02T09:02:34.683Z INF/device:plugins:group 34 [0000.............112B402E] Subscribing to group channel "q6NSYhnGSZiys4gGlZ4g0w=="
2023-11-02T09:02:35.796Z INF/wdaClient 34 [00008.............112B402E] verifying wda session status...
2023-11-02T09:02:35.820Z VRB/wdaClient 34 [0000803.............112B402E] Request has been sent to WDA with data:  {"method":"POST","uri":"http://appium:8100/session","body":{"capabilities":{}},"json":true}
2023-11-02T09:02:35.835Z VRB/wdaClient 34 [000080.............112B402E] Request has been sent to WDA with data:  {"method":"GET","uri":"http://appium:8100/status","json":true}
2023-11-02T09:02:35.836Z INF/wdaClient 34 [00008.............2B402E] status response: {"value":{"build":{"time":"Nov  1 2023 18:37:31","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"17.0","version":"17.0.2"},"device":"iphone","ios":{"ip":"192.168.89.36"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":"40700F40-9809-46DA-BC53-4D281BD19403"}
2023-11-02T09:02:35.837Z INF/wdaClient 34 [00008.............B402E] reusing existing wda session: 40700F40-9809-46DA-BC53-4D281BD19403
2023-11-02T09:02:35.839Z INF/wdaClient 34 [0000.............2B402E] Setting device version: 17.0.2
2023-11-02T09:02:35.841Z INF/wdaClient 34 [00008.............112B402E] getting device window size...
2023-11-02T09:02:35.994Z VRB/wdaClient 34 [00008.............112B402E] Request has been sent to WDA with data:  {"method":"GET","uri":"http://appium:8100/session/40700F40-9809-46DA-BC53-4D281BD19403/window/size"}
2023-11-02T09:02:36.006Z VRB/wdaClient 34 [00008.............2B402E] Request has been sent to WDA with data:  {"method":"GET","uri":"http://appium:8100/session/40700F40-9809-46DA-BC53-4D281BD19403/orientation","json":true}
2023-11-02T09:02:36.007Z INF/wdaClient 34 [0000.............8112B402E] Current device orientation: PORTRAIT
2023-11-02T09:02:36.207Z VRB/wdaClient 34 [0000.............2B402E] Request has been sent to WDA with data:  {"method":"GET","uri":"http://appium:8100/session/40700F40-9809-46DA-BC53-4D281BD19403/wda/screen"}
2023-11-02T09:02:38.445Z IMP/device:plugins:group 34 [000080.............448112B402E] No longer owned by "admin@fakedomain.com"
2023-11-02T09:02:38.446Z INF/device:plugins:group 34 [00008.............48112B402E] Unsubscribing from group channel "q6NSYhnGSZiys4gGlZ4g0w=="
2023-11-02T09:02:38.458Z INF/wdaClient 34 [00008.............2B402E] stopping wda session:  40700F40-9809-46DA-BC53-4D281BD19403
2023-11-02T09:02:38.459Z IMP/device:plugins:screen:stream 34 [000.............8112B402E] ws on close event
2023-11-02T09:02:38.472Z VRB/wdaClient 34 [00008.............112B402E] Request has been sent to WDA with data:  {"method":"DELETE","uri":"http://appium:8100/session/40700F40-9809-46DA-BC53-4D281BD19403"}
WdaMjpeg connection was closed
2023-11-02T09:02:41.640Z INF/util:lifecycle 34 [0000.............B402E] Winding down for graceful exit, with optional error :  WdaMjpeg connection is lost
2023-11-02T09:02:41.644Z FTL/util:lifecycle 34 [000.............2B402E] Shutting down due to fatal error with optional error :  WdaMjpeg connection is lost
Exit status: 1


```

**Comment by vdelendik** [comment] 2023-11-21 14:20
closing as can't reproduce... make sure to see you have loaded `~/Library/LaunchAgents/ZebrunnerDevicesListener.plist`
it is `com.zebrunner.mcloud` from about command.
```
launchctl list | grep zebrunner
>
-       0       com.zebrunner.mcloud.00008030-000C5448112B402E
43183   0       com.zebrunner.mcloud
617     0       com.zebrunner.usbmuxd
609     0       com.zebrunner.mcloud.bd03d002eae5d3087074198596cec3a0faf72a7d
-       0       com.zebrunner.mcloud.00008030-000315420285402E
```

Also, @tuyenlq, please provide `mcloud-agent/logs/agents.log` with disconnect and connect

**Closed by vdelendik** 2023-11-21 14:20 UTC
Labels: bug, invalid

**Comment by dhreben** [comment] 2023-11-27 10:31
Closed
