### ISSUE TITLE
dev/null on usr/local/bin/mcloud-devices.txt

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-agent#265] opened 2023-11-13 11:28 UTC
Global WDA is not set on usr/local/bin/mcloud-devices.txt

```
Samsung_A53|android|R..............V|7622|7624|7630|7623|7621|false|/dev/null|com.facebook.WebDriverAgentRunner.xctrunner
Pixel_7_2|android|2A3...................P|7632|7634|7640|7633|7631|false|/dev/null|com.facebook.WebDriverAgentRunner.xctrunner
Pixel_7A|android|2A..............0|7642|7644|7650|7643|7641|false|/dev/null|com.facebook.WebDriverAgentRunner.xctrunner
```

**Comment by vdelendik** [comment] 2023-11-21 20:56
closing as working as designed... the logic is implemented in such way:
1. `/dev/null` is registered inside /usr/local/bin/mcloud-devices.txt if no device related wda_file registered
2. on zebrunner-farm level we read global WDA_FILE and replace it with deviceWdaIpaPath if 2nd is not empty and not equal `/dev/null`

As result I see global WDA_FILE is successfully mounted on the appium container level:
```
            {
                "Type": "bind",
                "Source": "/home/build/tools/WebDriverAgent.ipa",
                "Destination": "/tmp/zebrunner/WebDriverAgent.ipa",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
```

in case of any problem with wda.ipa install it might be another problem.

@dhreben, let's re-test again using three variants:
1. only global value in WDA_FILE (TBD if we have to handle invalid WDA_FILE path detection... it might be a root cause of the original error because in this case docker generate empty folder for sharing)
2. only local wda_file declaration on the ios phones level
3. mix of WDA_FILE and wda_file for different devices

**Closed by vdelendik** 2023-11-21 20:56 UTC
Labels: bug, invalid

**Comment by vdelendik** [comment] 2023-11-21 21:24
it seems like extra echoing of the `/dev/null` for local wda_file in console log was printed mistakenly.
I updated log messages to print actual wda file path value we use for iOS devices, like:
```
wdaIpaPath: /home/build/tools/WebDriverAgent.ipa
wdaBundleId: com.facebook.WebDriverAgentRunner.xctrunner
```

removed invalid label as something was changed in the code
