### ISSUE TITLE
error":"Timed out waiting for response"

### ISSUE THREAD

**Issue by Immanuel-GWU** [zebrunner/mcloud-agent#145] opened 2022-10-14 06:35 UTC
After WDA installation is successful, facing a timed out error waiting for response from `com.apple.instruments.server.services.deviceinfo`

Device:
iPad 4th Gen(iPadOS v16)

Logs:
```
[23:00:24.079][3] usbmuxd v1.1.0 starting up
[23:00:24.084][3] Connecting to new device on location 0x1000d as ID 1
[23:00:24.084][3] Initialization complete
[23:00:24.084][3] Connected to v2.0 device 1 on location 0x1000d with serial number 00008101001D4CC20E05001E
Device is available
WARN! Unable to detect iOS device with udid: 00008101-001D4CC20E05001E.
DEVICE_UDID: 00008101001D4CC20E05001E
[13/10/2022 23:00:26] Pair device 00008101001D4CC20E05001E
{"level":"info","msg":"Successfully paired 00008101001D4CC20E05001E","time":"2022-10-13T23:00:26-07:00"}
[13/10/2022 23:00:26] populating device info
[13/10/2022 23:00:26] Mount /opt/zebrunner/DeveloperDiskImages/16.1/DeveloperDiskImage.dmg
{"level":"warning","msg":"there is already a developer image mounted, reboot the device if you want to remove it. aborting.","time":"2022-10-13T23:00:27-07:00"}
{"image":"/opt/zebrunner/DeveloperDiskImages/16.1/DeveloperDiskImage.dmg","level":"info","msg":"success mounting image","time":"2022-10-13T23:00:27-07:00","udid":"00008101001D4CC20E05001E"}
[13/10/2022 23:00:27] Installing WDA application on device
{"appPath":"/opt/WebDriverAgent.ipa","device":"00008101001D4CC20E05001E","level":"info","msg":"installing","time":"2022-10-13T23:00:27-07:00"}
{"level":"info","msg":"installing","percentComplete":5,"status":"CreatingStagingDirectory","time":"2022-10-13T23:00:28-07:00"}
{"level":"info","msg":"installing","percentComplete":15,"status":"ExtractingPackage","time":"2022-10-13T23:00:28-07:00"}
{"level":"info","msg":"installing","percentComplete":20,"status":"InspectingPackage","time":"2022-10-13T23:00:28-07:00"}
{"level":"info","msg":"installing","percentComplete":30,"status":"PreflightingApplication","time":"2022-10-13T23:00:28-07:00"}
{"level":"info","msg":"installing","percentComplete":40,"status":"VerifyingApplication","time":"2022-10-13T23:00:28-07:00"}
{"level":"info","msg":"installing","percentComplete":50,"status":"CreatingContainer","time":"2022-10-13T23:00:30-07:00"}
{"level":"info","msg":"installing","percentComplete":60,"status":"InstallingApplication","time":"2022-10-13T23:00:30-07:00"}
{"level":"info","msg":"installing","percentComplete":70,"status":"PostflightingApplication","time":"2022-10-13T23:00:30-07:00"}
{"level":"info","msg":"installing","percentComplete":80,"status":"SandboxingApplication","time":"2022-10-13T23:00:30-07:00"}
{"level":"info","msg":"installing","percentComplete":90,"status":"GeneratingApplicationMap","time":"2022-10-13T23:00:30-07:00"}
{"level":"info","msg":"installing","percentComplete":100,"status":"InstallComplete","time":"2022-10-13T23:00:30-07:00"}
{"level":"info","msg":"installation successful","time":"2022-10-13T23:00:30-07:00"}
[13/10/2022 23:00:30] Killing existing WebDriverAgent application if any
{"channel_id":"com.apple.instruments.server.services.deviceinfo","error":"Timed out waiting for response for message:5 channel:0","level":"error","msg":"failed requesting channel","time":"2022-10-13T23:00:35-07:00"}
{"level":"error","msg":"DeviceConnection failed writing 204 bytes, only 0 sent","time":"2022-10-13T23:00:35-07:00"}
{"level":"error","msg":"Failed sending: write unix @-\u003e/var/run/usbmuxd: write: broken pipe","time":"2022-10-13T23:00:35-07:00"}
{"channel_id":"com.apple.instruments.server.services.deviceinfo","error":"write unix @-\u003e/var/run/usbmuxd: write: broken pipe","level":"info","methodselector":"runningProcesses","msg":"failed starting invoking method","time":"2022-10-13T23:00:35-07:00"}
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/danielpaulus/go-ios/ios/instruments.DeviceInfoService.ProcessList({0xc000072660, 0xc0002cfa00})
        /home/runner/work/go-ios/go-ios/ios/instruments/processlist.go:26 +0x137
main.Main()
        /home/runner/work/go-ios/go-ios/main.go:493 +0x1551
main.main()
        /home/runner/work/go-ios/go-ios/main.go:46 +0x17
[13/10/2022 23:00:35] Starting WebDriverAgent application on port 8100
detecting WDA_HOST ip address...
attempt 1
attempt 2
attempt 3
attempt 4
attempt 5
attempt 6
attempt 7
attempt 8
attempt 9
attempt 10
attempt 11
attempt 12
attempt 13
attempt 14
attempt 15
attempt 16
attempt 17
attempt 18
attempt 19
attempt 20
attempt 21
attempt 22
attempt 23
attempt 24
attempt 25
attempt 26
attempt 27
attempt 28
attempt 29
attempt 30
ERROR! Unable to parse WDA_HOST ip from log file!
{"bundleid":"com.facebook.WebDriverAgentRunner.xctrunner","level":"info","msg":"Running wda","testbundleid":"com.facebook.WebDriverAgentRunner.xctrunner","time":"2022-10-13T23:00:35-07:00","xctestconfig":"WebDriverAgentRunner.xctest"}
{"error":"Did not find AppInfo for 'com.facebook.WebDriverAgentRunner.xctrunner' on device. Is it installed?","level":"fatal","msg":"Failed running WDA","time":"2022-10-13T23:00:35-07:00"}
Detected WDA_HOST ip: 
WDA_PORT=8100
[13/10/2022 23:01:05] Starting WebDriverAgent 1st session
WDA session response:
bundleId:
sessionId:
[13/10/2022 23:01:05] Activating springboard app forcibly
[13/10/2022 23:01:06] Stopping 1st default WebDriverAgent session
sessionId:

Connecting to  8101 using netcat...
no port[s] to connect to
netcat connection is closed.
[13/10/2022 23:01:06] Killing existing WebDriverAgent application if any
{
  "capabilities":
      [
        {
          "maxInstances": 1,
          "deviceName": "iPad",
          "deviceType": "Tablet",
          "platformName":"ios",
          "platformVersion":"16.1",
          "udid": "00008101001D4CC20E05001E",
          "adb_port": 7732,
          "proxy_port": 7733,
          "automationName": "XCUITest"
        }
      ],
  "configuration":
  {
    "proxy": "com.zebrunner.mcloud.grid.MobileRemoteProxy",
    "url":"http://192.168.5.172:7731/wd/hub",
    "host": "192.168.5.172",
    "port": 7731,
    "hubHost": "mcloud-grid",
    "hubPort": 4444,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "cleanUpCycle": 5000,
    "timeout": 180,
    "browserTimeout": 0,
    "nodeStatusCheckTimeout": 5000,
    "nodePolling": 5000,
    "role": "node",
    "unregisterIfStillDownAfter": 60000,
    "downPollingLimit": 2,
    "debug": false,
    "servlets" : [],
    "withoutServlets": [],
    "custom": {}
  }
}
{
 "udid":"00008101001D4CC20E05001E",
 "mjpegServerPort": 8101,
 "clearSystemFiles": "false",
 "webDriverAgentUrl":"http://:8100",
 "preventWDAAttachments": "true",
 "simpleIsVisibleCheck": "true",
 "wdaLocalPort": "8100",
 "platformVersion": "16.1",
 "automationName":"XCUITest",
 "platformName": "ios",
 "deviceName": "iPad",
 "provider": "mcloud",
 "enableVideo": "true",
 "enableLog": "true",
 "enableVnc": "false"
}
'/opt/mcloud/appium-patch.sh' -> '/usr/lib/node_modules/appium/appium-patch.sh'
'/opt/mcloud/build/lib/grid-register.js' -> '/usr/lib/node_modules/appium/build/lib/grid-register.js' (backup: '/usr/lib/node_modules/appium/build/lib/grid-register.js.~1~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js.~1~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/basedriver/driver.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/driver.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/driver.js.~1~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/basedriver/helpers.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/helpers.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/helpers.js.~1~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/basedriver/mcloud-utils.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/mcloud-utils.js'
'/opt/mcloud/node_modules/appium-base-driver/build/lib/protocol/protocol.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/protocol.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/protocol.js.~1~')
'/opt/mcloud/node_modules/appium-base-driver/build/lib/protocol/routes.js' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/routes.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/routes.js.~1~')
'/opt/mcloud/node_modules/appium-base-driver-7_10_0.diff' -> '/usr/lib/node_modules/appium/node_modules/appium-base-driver-7_10_0.diff'
'/opt/mcloud/node_modules/appium-xcuitest-driver/build/lib/ios-deploy.js' -> '/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/ios-deploy.js' (backup: '/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/ios-deploy.js.~1~')
'/opt/mcloud/node_modules/appium-xcuitest-driver-3_53_1.diff' -> '/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver-3_53_1.diff'
xvfb-run appium --log-no-colors --log-timestamp --log /var/log/appium.log --session-override --nodeconfig /root/nodeconfig.json --default-capabilities /root/defaultcapabilities.json --relaxed-security --allow-insecure chromedriver_autodownload
[info] [AppiumEntryPoint] registering upload method on SIGTERM
[info] [AppiumEntryPoint] waiting until SIGTERM received
Exit status: 1
```
Help is much appreciated @vdelendik

**Comment by vdelendik** [comment] 2022-12-14 21:01
@Immanuel-GWU, closing as duplicate of https://github.com/zebrunner/appium/issues/111
the only workaround so far - reboot iOS device after this exception

**Closed by vdelendik** 2022-12-14 21:01 UTC
Labels: duplicate
