### ISSUE TITLE
WdaMjpeg connection was closed iOS 17.4-17.5 continue 

### ISSUE THREAD

**Issue by yaroslav796** [zebrunner/mcloud-agent#333] opened 2024-07-23 13:27 UTC
continue [https://github.com/zebrunner/mcloud-agent/issues/317](url)
Hi!
Restarting the device and using a different WebDriverAgent did not help. The main container still keeps restarting and crashing. I tried to connect to the phone using Appium Inspector through the running Appium container. I managed to connect to the phone, but there was no image.

However, if I install Appium on my computer and connect to the device, the connection and image are present.

I suspect the issue might be related to the version of the XCUITest driver. Inside the container, it is running XCUITest@5.7.0, while the new version I tested with is XCUITest@7.24.1. But this is just a guess.

[appium.log](https://github.com/user-attachments/files/16349471/appium.log)
[Main container.txt](https://github.com/user-attachments/files/16349496/Main.container.txt)

**Comment by vdelendik** [comment] 2024-07-27 09:17
@yaroslav796, please try to upgrade to the latest v2.7:
https://github.com/zebrunner/mcloud/releases/tag/2.7

**Comment by yaroslav796** [comment] 2024-07-29 13:38
Updated the project^
It didn't help.

**Comment by vdelendik** [comment] 2024-09-12 13:56
closing as can't reproduce. need more details here.

**Closed by vdelendik** 2024-09-12 13:56 UTC
Labels: bug
